### ISSUE TITLE
using more than one tick for inline code blocks isn't parsed correctly

### ISSUE THREAD

**Issue by apatrida** [valich/intellij-markdown#13] opened 2016-06-25 07:03 UTC
It doesn't appear that if you do:

```inline`with`ticks`inside``` that the parsing keeps the inside ticks.

whereas github and other renderers handle this as the screenshot shows:
![screen shot 2016-06-25 at 4 02 21 am](https://cloud.githubusercontent.com/assets/182340/16355319/b07ede6e-3a89-11e6-8b4a-7ee659261ed7.png)

**Comment by valich** [comment] 2016-06-25 21:19
Hi @apatrida,

I could not reproduce the case. Are you sure it's not a renderer problem? The easiest way to check the parser if you're using IJ is to install the latest `Markdown Support` plugin and see what it renders with JavaFX preview.

**Comment by valich** [comment] 2019-10-24 13:55
Closing as obsolete

**Closed by valich** 2019-10-24 13:55 UTC
